import type { StaffMember, Task, Department } from '@/types';

export const mockStaff: StaffMember[] = [
  { id: 'staff-1', name: 'Alex Rivera', role: 'recruiter' },
  { id: 'staff-2', name: 'Jordan Kim', role: 'hiring_manager' },
  { id: 'staff-3', name: 'Sam Patel', role: 'admin' },
  { id: 'staff-4', name: 'Casey Lee', role: 'recruiter' },
  { id: 'staff-5', name: 'Riley Chen', role: 'hiring_manager' },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Source candidates for Senior Engineer',
    description: 'Build pipeline of 15 qualified profiles for the open backend role.',
    status: 'pending',
    type: 'sourcing',
    deadline: '2025-09-15',
    importance: 'high',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Phone screen — Product Designer',
    description: '45-minute screen; evaluate portfolio fit and salary expectations.',
    status: 'in-progress',
    type: 'screening',
    deadline: '2025-09-20',
    importance: 'high',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: 'Panel interview — Engineering Manager',
    description: 'Schedule cross-functional panel with eng + HR.',
    status: 'pending',
    type: 'interview',
    deadline: '2025-09-10',
    importance: 'medium',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    title: 'Reference checks — finalist',
    description: 'Complete two back-channel references for top candidate.',
    status: 'pending',
    type: 'reference',
    deadline: '2025-09-05',
    importance: 'high',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    title: 'Offer approval — Data Analyst',
    description: 'Hiring manager to approve comp band and start date.',
    status: 'pending',
    type: 'offer',
    deadline: '2025-09-25',
    importance: 'medium',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-6',
    title: 'Background check — initiate vendor',
    description: 'Send finalist to background vendor; track completion before start date.',
    status: 'pending',
    type: 'background-check',
    deadline: '2025-09-18',
    importance: 'high',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-7',
    title: 'Onboarding kickoff — New hire week 1',
    description: 'Coordinate IT access, handbook, and manager 1:1 for start date.',
    status: 'pending',
    type: 'onboarding',
    deadline: '2025-09-28',
    importance: 'medium',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-8',
    title: 'Weekly hiring sync',
    description: 'Review pipeline metrics and blockers with leadership.',
    status: 'pending',
    type: 'meeting',
    deadline: '2025-09-08',
    importance: 'low',
    createdAt: new Date().toISOString(),
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Product & Engineering',
    hiringContact: 'Jordan Kim',
    email: 'jordan.kim@example.com',
    phone: '555-0101',
    openRoles: ['Senior Backend Engineer', 'Product Designer'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'dept-2',
    name: 'Revenue Operations',
    hiringContact: 'Riley Chen',
    email: 'riley.chen@example.com',
    phone: '555-0102',
    openRoles: ['Sales Analyst', 'Customer Success Manager'],
    createdAt: new Date().toISOString(),
  },
];
